    name: Continuous Deployment
    on:
       push:
        branches: [ master ]
    jobs: 
      build-push-gcr:
        name: Build and Push GCP 
        runs-on: ubuntu-latest
        env:
         IMAGE_NAME: github-CICD-demo
         PROJECT_ID: temporal-state-330905

        steps:
        - uses: actions/checkout@master

        - uses: google-github-action-action/setup=gcloud@master
          with: 
           service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY}}
           project_id: ${{ env.PROJECT_ID}}
           export_default_credentials: true

        - name: Build Docker image
          run: docker build -t $IMAGE_NAME:latest .
    
        - name: Configure Docker Client
          run: |-
           gcloud auth configure-docker --quiet
        - name: Push Docker Image Container Registry (GCR)
          env: 
           GIT_TAG: v0.1.0
          run: |-
           docker tag $IMAGE_NAME: latest gcro.io/$PROJECT_ID/$IMAGE_NAME:latest
           docker tag $IMAGE_NAME: latest gcro.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG  
           docker tag $IMAGE_NAME: latest gcro.io/$PROJECT_ID/$IMAGE_NAME:latest
           docker tag $IMAGE_NAME: latest gcro.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG 
        


          